apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:  
    - port: 80 # posso definir apenas port, pois por padrão, nodePort e TaretPort receberão os mesmo valore de port.
      nodePort: 30001
      # targetPort: 30000 -> implícito 
  selector:
    app: sistema-noticias